# Generated by Django 4.2.15 on 2024-08-27 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_rename_addevents_addevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='addevent',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='addevent',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attending_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_attending', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendees', to='event.addevent')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('attending_user', 'event')},
            },
        ),
    ]
