# Generated by Django 4.2.15 on 2024-08-28 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_addevent_excerpt_addevent_updated_on_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='addevent',
            options={'ordering': ['start_date_time'], 'verbose_name': 'Add Event', 'verbose_name_plural': 'Add Events'},
        ),
        migrations.AlterModelOptions(
            name='attending',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Attending', 'verbose_name_plural': 'Users Attending'},
        ),
        migrations.RemoveField(
            model_name='addevent',
            name='end_date',
        ),
        migrations.AddField(
            model_name='addevent',
            name='end_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='addevent',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='link_to_event_page',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='location',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attending',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='event.addevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='addevent',
            name='event_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.category'),
        ),
    ]
