# Generated by Django 4.2.15 on 2024-08-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_addevent_excerpt_addevent_updated_on_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='addevent',
            options={'ordering': ['start_date_time'], 'verbose_name': 'Add Event', 'verbose_name_plural': 'Add Events'},
        ),
        migrations.AlterModelOptions(
            name='attending',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Attending', 'verbose_name_plural': 'Users Attending'},
        ),
        migrations.AlterField(
            model_name='addevent',
            name='location',
            field=models.CharField(blank=True),
        ),
    ]
